name: Release IOS
on: workflow_dispatch
jobs:
  iOS:
     runs-on: macos-14
     steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v4
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-ios
          path: |
            .haxelib/
            export/release/ios/PibbyApocalypse/haxe/
          restore-keys: |
            cache-build-ios
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib git hxcpp https://github.com/kittycathy233/hxcpp --quiet
          haxelib git lime https://github.com/Ethantobot11/lime-for-PA-OLD-PORT --quiet
          haxelib install openfl 9.2.2 --quiet
          haxelib --never install flixel 5.2.2 --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui 2.4.0 --quiet
          haxelib install flixel-addons 2.11.0 --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hscript --quiet
          haxelib install hxvlc 1.9.0 --quiet
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git --quiet
          haxelib install hxcpp-debug-server --quiet
          haxelib list
      #  haxelib run lime rebuild extension-iostools ios -arm64 -final

      - name: Clearing already existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-ios") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Setup Lime
        run: |
          haxelib set lime git
          haxelib set openfl 9.2.2 --always
          haxelib set flixel 5.2.2 --always
          haxelib set hxvlc 1.9.0 --always
          haxelib set flixel-ui 2.4.0 --always
          haxelib set flixel-addons 2.11.0 --always
          haxelib set hxcpp git
    # sb 报错666

      # - name: Install MobileVLCKit Framework
        # run: |
          # cd ${{ github.workspace }}/..
          # wget -q https://download.videolan.org/cocoapods/prod/MobileVLCKit-3.5.1-34408b84-e9eceaed.tar.xz
          # tar -xf MobileVLCKit-3.5.1-34408b84-e9eceaed.tar.xz

      - name: Compile
        run: haxelib run lime build ios -final -nosign -DHXCPP_ARM64 -DNO_SIGN -DHXCPP_TARGET_IOS_MIN_VERSION=12.0 -DHXCPP_IOS_ARCHS=arm64


      # - name: Check Code Signing
        # run: cd export/release/ios/build/Release-iphoneos && codesign -dv *.app

      - name: Make Ipa
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r Pibby：Apocalypse.ipa Payload
      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error

      - name: Uploading new cache
        uses: actions/cache@v4
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-ios
          path: |
            .haxelib/
            export/release/ios/PibbyApocalypse/haxe/
          restore-keys: |
            cache-build-ios
